knox_protocol: https
knox_port: 8443
domain: knoxexample.com
webserver_service: httpd
knox_topology_src_dir: /usr/hdp/current/knox-server/conf/topologies
knox_security_keystore_dir: /usr/hdp/current/knox-server/data/security/keystores
knox_topology_dir: /etc/knox/conf/topologies/
